### ISSUE TITLE
rest client: feat: Add `expiretm` to User-Trading/operation/addOrder

### ISSUE THREAD

**Issue by gitmalong** [gmosx/kraken-sdk-rust#29]
Hi!

Currently the add limit order fn does not support adding an expire timestamp.

https://docs.kraken.com/rest/#tag/User-Trading/operation/addOrder

And a general question: Have you considered to auto-generate certain API calls and structs with help of the OpenAPI JSON?

**Comment by gmosx** [comment]
The OpenAPI suggestion is interesting. I don't have much time at the moment, but I would appreciate it if you could open a separate issue just for that.

**Comment by gmosx** [comment]
Seems to me that `expiretm` is supported.

**Comment by gmosx** [comment]
Added support for effective/expire time in WS client. 'REST' client already supports this.
